-- ============================================================================
-- SPS Retail Fulfillment Intelligence — Table Creation & Data Load
-- Step 2: Create tables and load from staged CSV files
-- Run AFTER 01_environment.sql and upload_data.sh
-- ============================================================================

USE DATABASE SPS_RETAIL_AI;
USE SCHEMA SHARED;

-- ── Dimension Tables ────────────────────────────────────────

CREATE OR REPLACE TABLE RETAILER (
    RETAILER_ID VARCHAR(20) NOT NULL,
    RETAILER_NAME VARCHAR(100) NOT NULL,
    ENTERPRISE_NAME VARCHAR(100),
    INDUSTRY_SEGMENT VARCHAR(50),
    DEFAULT_CURRENCY VARCHAR(3) DEFAULT 'USD',
    DEFAULT_TIMEZONE VARCHAR(50) DEFAULT 'America/New_York',
    EDI_PARTNER VARCHAR(50),
    PO_REVISION_METHOD VARCHAR(20),
    USES_UPC BOOLEAN DEFAULT TRUE,
    ACTIVITY_GRAIN VARCHAR(10) DEFAULT 'WEEKLY',
    IS_SYNTHETIC BOOLEAN DEFAULT TRUE,
    CONSTRAINT PK_RETAILER PRIMARY KEY (RETAILER_ID)
);

CREATE OR REPLACE TABLE SUPPLIER (
    SUPPLIER_ID VARCHAR(20) NOT NULL,
    SUPPLIER_NAME VARCHAR(100),
    REGION VARCHAR(50),
    COUNTRY VARCHAR(50),
    CATEGORY_SPECIALTY VARCHAR(100),
    RELIABILITY_TIER VARCHAR(10),
    AVG_LEAD_DAYS NUMBER,
    LEAD_VARIABILITY_DAYS NUMBER,
    ONBOARDED_DATE DATE,
    IS_SYNTHETIC BOOLEAN DEFAULT TRUE,
    CONSTRAINT PK_SUPPLIER PRIMARY KEY (SUPPLIER_ID)
);

CREATE OR REPLACE TABLE LOCATION (
    LOCATION_ID VARCHAR(20) NOT NULL,
    RETAILER_ID VARCHAR(20),
    SPS_RETAILER_NAME_KEY VARCHAR(100),
    SPS_CUSTOMER_LOCATION_KEY VARCHAR(100),
    STORE_NUMBER VARCHAR(20),
    STORE_NAME VARCHAR(200),
    LOCATION_TYPE VARCHAR(50),
    ADDRESS VARCHAR(500),
    CITY VARCHAR(100),
    STATE VARCHAR(50),
    POSTAL_CODE VARCHAR(20),
    COUNTRY VARCHAR(50),
    SPS_COUNTRY_CODE VARCHAR(10),
    SPS_COUNTRY VARCHAR(100),
    SPS_LATITUDE NUMBER(10,6),
    SPS_LONGITUDE NUMBER(10,6),
    REGION VARCHAR(50),
    CLIMATE VARCHAR(50),
    BANNER VARCHAR(100),
    STORE_CLASSIFICATION VARCHAR(50),
    STORE_SIZE VARCHAR(20),
    OPEN_DATE DATE,
    CLOSE_DATE DATE,
    CURRENCY_CODE VARCHAR(3),
    IS_SYNTHETIC BOOLEAN DEFAULT TRUE,
    CONSTRAINT PK_LOCATION PRIMARY KEY (LOCATION_ID)
);

CREATE OR REPLACE TABLE ITEM (
    ITEM_ID VARCHAR(20) NOT NULL,
    RETAILER_ID VARCHAR(20),
    SPS_RETAILER_NAME_KEY VARCHAR(100),
    SPS_CUSTOMER_ITEM_KEY VARCHAR(100),
    SPS_ITEM_MAPPING_KEY VARCHAR(100),
    CATEGORY_NAME VARCHAR(100),
    PRODUCT_GROUP_NAME VARCHAR(100),
    GENDER VARCHAR(20),
    STYLE_NUMBER VARCHAR(50),
    STYLE_DESCRIPTION VARCHAR(500),
    COLOR_NAME VARCHAR(100),
    SIZE_NAME VARCHAR(50),
    UPC VARCHAR(20),
    SKU VARCHAR(50),
    URBN_SHORT_SKU VARCHAR(50),
    VENDOR_STYLE_NUMBER VARCHAR(50),
    PRODUCT_DESCRIPTION VARCHAR(500),
    MSRP NUMBER(10,2),
    COST NUMBER(10,2),
    BRAND_NAME VARCHAR(100),
    VENDOR_CODE VARCHAR(20),
    VENDOR_NAME VARCHAR(200),
    SUPPLIER_ID VARCHAR(20),
    DEPARTMENT_NAME VARCHAR(100),
    PRODUCT_SEASON VARCHAR(50),
    REPLENISHMENT_INDICATOR VARCHAR(10),
    LAUNCH_DATE DATE,
    EXIT_DATE DATE,
    UNIT_OF_MEASURE VARCHAR(20),
    SPS_ITEM_STATUS VARCHAR(20),
    IS_SYNTHETIC BOOLEAN DEFAULT TRUE,
    INSERT_TIMESTAMP TIMESTAMP_NTZ,
    CONSTRAINT PK_ITEM PRIMARY KEY (ITEM_ID)
);

CREATE OR REPLACE TABLE RETAIL_CALENDAR (
    CALENDAR_DATE DATE NOT NULL,
    FISCAL_WEEK VARCHAR(20),
    FISCAL_YEAR NUMBER,
    WEEK_NUMBER NUMBER,
    MONTH_NAME VARCHAR(20),
    QUARTER VARCHAR(10),
    SEASON VARCHAR(20),
    IS_HOLIDAY_WEEK BOOLEAN,
    HOLIDAY_NAME VARCHAR(100),
    CONSTRAINT PK_RETAIL_CALENDAR PRIMARY KEY (CALENDAR_DATE)
);

-- ── Transaction Tables ──────────────────────────────────────

CREATE OR REPLACE TABLE PURCHASE_ORDER (
    PO_ID VARCHAR(50) NOT NULL,
    PO_NUMBER VARCHAR(50),
    PO_VERSION NUMBER,
    RETAILER_ID VARCHAR(20),
    SUPPLIER_ID VARCHAR(20),
    SHIP_TO_LOCATION_ID VARCHAR(20),
    ORDER_DATE DATE,
    REQUESTED_SHIP_DATE DATE,
    REQUESTED_DELIVERY_DATE DATE,
    PO_STATUS VARCHAR(20),
    REVISION_TYPE VARCHAR(50),
    IS_REPLACEMENT_850 BOOLEAN,
    ORIGINAL_PO_ID VARCHAR(50),
    CURRENCY VARCHAR(3),
    TOTAL_UNITS NUMBER,
    TOTAL_COST NUMBER(12,2),
    TOTAL_RETAIL NUMBER(12,2),
    ACCEPTANCE_STATUS VARCHAR(20),
    ACCEPTED_AT TIMESTAMP_NTZ,
    IS_SYNTHETIC BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE PO_LINE (
    PO_LINE_ID VARCHAR(50) NOT NULL,
    PO_ID VARCHAR(50),
    LINE_NUMBER NUMBER,
    ITEM_ID VARCHAR(20),
    ORDERED_QTY NUMBER,
    UNIT_PRICE NUMBER(10,2),
    LINE_TOTAL NUMBER(12,2),
    LINE_STATUS VARCHAR(20),
    SHIPPED_QTY NUMBER,
    RECEIVED_QTY NUMBER,
    INVOICED_QTY NUMBER,
    IS_SYNTHETIC BOOLEAN DEFAULT TRUE
);

CREATE OR REPLACE TABLE SHIPMENT (
    SHIPMENT_ID VARCHAR(50) NOT NULL,
    ASN_NUMBER VARCHAR(50),
    PO_ID VARCHAR(50),
    SUPPLIER_ID VARCHAR(20),
    RETAILER_ID VARCHAR(20),
    ORIGIN_LOCATION VARCHAR(200),
    DESTINATION_LOCATION_ID VARCHAR(20),
    CARRIER VARCHAR(100),
    SHIP_DATE DATE,
    ESTIMATED_DELIVERY_DATE DATE,
    ACTUAL_DELIVERY_DATE DATE,
    SHIPMENT_STATUS VARCHAR(20),
    TOTAL_UNITS NUMBER,
    TOTAL_CARTONS NUMBER,
    ON_TIME_FLAG BOOLEAN,
    IN_FULL_FLAG BOOLEAN,
    IS_SYNTHETIC BOOLEAN DEFAULT TRUE
);

CREATE OR REPLACE TABLE RECEIPT (
    RECEIPT_ID VARCHAR(50) NOT NULL,
    SHIPMENT_ID VARCHAR(50),
    PO_ID VARCHAR(50),
    LOCATION_ID VARCHAR(20),
    RETAILER_ID VARCHAR(20),
    RECEIPT_DATE DATE,
    TOTAL_RECEIVED_UNITS NUMBER,
    TOTAL_DAMAGED_UNITS NUMBER,
    RECEIPT_STATUS VARCHAR(20),
    DAYS_LATE NUMBER,
    IS_SYNTHETIC BOOLEAN DEFAULT TRUE
);

CREATE OR REPLACE TABLE INVOICE (
    INVOICE_ID VARCHAR(50) NOT NULL,
    INVOICE_NUMBER VARCHAR(50),
    PO_ID VARCHAR(50),
    SHIPMENT_ID VARCHAR(50),
    SUPPLIER_ID VARCHAR(20),
    RETAILER_ID VARCHAR(20),
    INVOICE_DATE DATE,
    DUE_DATE DATE,
    INVOICE_TOTAL NUMBER(12,2),
    PAYMENT_STATUS VARCHAR(20),
    MISMATCH_FLAG BOOLEAN,
    MISMATCH_REASON VARCHAR(200),
    IS_SYNTHETIC BOOLEAN DEFAULT TRUE
);

-- ── SPS Activity (fact table) ───────────────────────────────

CREATE OR REPLACE TABLE SPS_ACTIVITY (
    SPS_CUSTOMER_ITEM_KEY VARCHAR(100),
    SPS_RETAILER_NAME_KEY VARCHAR(100),
    SPS_CUSTOMER_LOCATION_KEY VARCHAR(100),
    SPS_ITEM_MAPPING_KEY VARCHAR(100),
    PERIOD_ENDING_DATE NUMBER,
    NET_SALES_UNITS NUMBER,
    NET_SALES_RETAIL NUMBER(12,2),
    INVENTORY_UNITS NUMBER,
    ON_ORDER_UNITS NUMBER,
    RECEIPT_UNITS NUMBER,
    IN_TRANSIT_UNITS NUMBER,
    CUSTOMER_RETURN_UNITS NUMBER,
    TOTAL_MARKDOWN_VALUES FLOAT,
    CORPORATE_UNIT_ADJUSTED_COST NUMBER(10,2),
    CORPORATE_UNIT_ACQUIRED_COST NUMBER(10,2),
    CORPORATE_UNIT_OWNED_RETAIL_PRICE NUMBER(10,2),
    RETAILER_ID VARCHAR(20),
    ITEM_ID VARCHAR(20),
    LOCATION_ID VARCHAR(20),
    CATEGORY_NAME VARCHAR(100),
    PRODUCT_GROUP_NAME VARCHAR(100),
    SEASON VARCHAR(20),
    FISCAL_YEAR NUMBER,
    IS_HOLIDAY_WEEK BOOLEAN,
    ACTIVITY_GRAIN VARCHAR(10),
    INSERT_TIMESTAMP TIMESTAMP_NTZ,
    IS_SYNTHETIC BOOLEAN DEFAULT TRUE
);

-- ── Urban Outfitters SKU Crosswalk ──────────────────────────

CREATE OR REPLACE TABLE URBAN_OUTFITTERS.SKU_CROSSWALK (
    ITEM_ID VARCHAR(20),
    URBN_SHORT_SKU VARCHAR(50),
    VENDOR_UPC VARCHAR(20),
    VENDOR_STYLE_NUMBER VARCHAR(50),
    STYLE_NUMBER VARCHAR(50),
    COLOR_NAME VARCHAR(100),
    SIZE_NAME VARCHAR(50),
    MAPPING_STATUS VARCHAR(20),
    VALID_FROM DATE,
    VALID_TO DATE,
    LAST_VERIFIED_AT TIMESTAMP_NTZ
);

-- ── ML Training Data ────────────────────────────────────────

CREATE OR REPLACE TABLE ML_MODELS.TRAINING_DATA (
    PO_ID VARCHAR(50),
    RETAILER_ID VARCHAR(20),
    SUPPLIER_ID VARCHAR(20),
    TOTAL_UNITS NUMBER,
    TOTAL_COST NUMBER(12,2),
    PO_VERSION NUMBER,
    IS_REPLACEMENT_850 BOOLEAN,
    SUPPLIER_AVG_LEAD NUMBER(10,1),
    SUPPLIER_LEAD_VAR FLOAT,
    SUPPLIER_REGION VARCHAR(50),
    DESTINATION_REGION VARCHAR(50),
    DESTINATION_SIZE VARCHAR(20),
    LOCATION_TYPE VARCHAR(50),
    ORDER_DOW NUMBER,
    ORDER_MONTH NUMBER,
    DAYS_TO_DELIVER NUMBER,
    DAYS_TO_SHIP NUMBER,
    LINE_COUNT NUMBER,
    TOTAL_LINE_QTY NUMBER,
    DISTINCT_ITEMS NUMBER,
    HIST_ON_TIME_RATE NUMBER(5,3),
    HIST_IN_FULL_RATE NUMBER(5,3),
    HIST_OTIF_RATE NUMBER(5,3),
    HIST_AVG_DAYS_LATE NUMBER(10,1),
    HIST_PO_COUNT NUMBER,
    IS_LATE_OR_SHORT NUMBER
);

-- ── Load Data from Stage ────────────────────────────────────

COPY INTO SHARED.RETAILER FROM @SPS_RETAIL_AI.PUBLIC.DATA_STAGE/shared/retailer.csv FILE_FORMAT = (FORMAT_NAME = 'SPS_RETAIL_AI.PUBLIC.CSV_FORMAT');
COPY INTO SHARED.SUPPLIER FROM @SPS_RETAIL_AI.PUBLIC.DATA_STAGE/shared/supplier.csv FILE_FORMAT = (FORMAT_NAME = 'SPS_RETAIL_AI.PUBLIC.CSV_FORMAT');
COPY INTO SHARED.LOCATION FROM @SPS_RETAIL_AI.PUBLIC.DATA_STAGE/shared/location.csv FILE_FORMAT = (FORMAT_NAME = 'SPS_RETAIL_AI.PUBLIC.CSV_FORMAT');
COPY INTO SHARED.ITEM FROM @SPS_RETAIL_AI.PUBLIC.DATA_STAGE/shared/item.csv FILE_FORMAT = (FORMAT_NAME = 'SPS_RETAIL_AI.PUBLIC.CSV_FORMAT');
COPY INTO SHARED.RETAIL_CALENDAR FROM @SPS_RETAIL_AI.PUBLIC.DATA_STAGE/shared/retail_calendar.csv FILE_FORMAT = (FORMAT_NAME = 'SPS_RETAIL_AI.PUBLIC.CSV_FORMAT');
COPY INTO SHARED.PURCHASE_ORDER FROM @SPS_RETAIL_AI.PUBLIC.DATA_STAGE/shared/purchase_order.csv FILE_FORMAT = (FORMAT_NAME = 'SPS_RETAIL_AI.PUBLIC.CSV_FORMAT');
COPY INTO SHARED.PO_LINE FROM @SPS_RETAIL_AI.PUBLIC.DATA_STAGE/shared/po_line.csv FILE_FORMAT = (FORMAT_NAME = 'SPS_RETAIL_AI.PUBLIC.CSV_FORMAT');
COPY INTO SHARED.SHIPMENT FROM @SPS_RETAIL_AI.PUBLIC.DATA_STAGE/shared/shipment.csv FILE_FORMAT = (FORMAT_NAME = 'SPS_RETAIL_AI.PUBLIC.CSV_FORMAT');
COPY INTO SHARED.RECEIPT FROM @SPS_RETAIL_AI.PUBLIC.DATA_STAGE/shared/receipt.csv FILE_FORMAT = (FORMAT_NAME = 'SPS_RETAIL_AI.PUBLIC.CSV_FORMAT');
COPY INTO SHARED.INVOICE FROM @SPS_RETAIL_AI.PUBLIC.DATA_STAGE/shared/invoice.csv FILE_FORMAT = (FORMAT_NAME = 'SPS_RETAIL_AI.PUBLIC.CSV_FORMAT');

-- SPS_ACTIVITY is gzip compressed
COPY INTO SHARED.SPS_ACTIVITY FROM @SPS_RETAIL_AI.PUBLIC.DATA_STAGE/shared/sps_activity.csv.gz
  FILE_FORMAT = (TYPE='CSV' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1 NULL_IF=('','NULL') COMPRESSION='GZIP');

COPY INTO URBAN_OUTFITTERS.SKU_CROSSWALK FROM @SPS_RETAIL_AI.PUBLIC.DATA_STAGE/urban_outfitters/sku_crosswalk.csv FILE_FORMAT = (FORMAT_NAME = 'SPS_RETAIL_AI.PUBLIC.CSV_FORMAT');
COPY INTO ML_MODELS.TRAINING_DATA FROM @SPS_RETAIL_AI.PUBLIC.DATA_STAGE/ml_models/training_data.csv FILE_FORMAT = (FORMAT_NAME = 'SPS_RETAIL_AI.PUBLIC.CSV_FORMAT');

-- ── Verify Loads ────────────────────────────────────────────
SELECT 'RETAILER' AS TBL, COUNT(*) AS ROWS FROM SHARED.RETAILER
UNION ALL SELECT 'SUPPLIER', COUNT(*) FROM SHARED.SUPPLIER
UNION ALL SELECT 'LOCATION', COUNT(*) FROM SHARED.LOCATION
UNION ALL SELECT 'ITEM', COUNT(*) FROM SHARED.ITEM
UNION ALL SELECT 'RETAIL_CALENDAR', COUNT(*) FROM SHARED.RETAIL_CALENDAR
UNION ALL SELECT 'PURCHASE_ORDER', COUNT(*) FROM SHARED.PURCHASE_ORDER
UNION ALL SELECT 'PO_LINE', COUNT(*) FROM SHARED.PO_LINE
UNION ALL SELECT 'SHIPMENT', COUNT(*) FROM SHARED.SHIPMENT
UNION ALL SELECT 'RECEIPT', COUNT(*) FROM SHARED.RECEIPT
UNION ALL SELECT 'INVOICE', COUNT(*) FROM SHARED.INVOICE
UNION ALL SELECT 'SPS_ACTIVITY', COUNT(*) FROM SHARED.SPS_ACTIVITY
UNION ALL SELECT 'SKU_CROSSWALK', COUNT(*) FROM URBAN_OUTFITTERS.SKU_CROSSWALK
UNION ALL SELECT 'TRAINING_DATA', COUNT(*) FROM ML_MODELS.TRAINING_DATA
ORDER BY TBL;
