-- ============================================================================
-- SPS Retail Fulfillment Intelligence — Views
-- Step 3: Analytical views for dashboards
-- Run AFTER 02_load_data.sql
-- ============================================================================

USE DATABASE SPS_RETAIL_AI;

-- ── Cross-Retailer KPI View ─────────────────────────────────
CREATE OR REPLACE VIEW SHARED.V_FULFILLMENT_KPI AS
SELECT
    r.RETAILER_NAME,
    po.RETAILER_ID,
    COUNT(DISTINCT po.PO_ID) AS TOTAL_POS,
    COUNT(DISTINCT sh.SHIPMENT_ID) AS TOTAL_SHIPMENTS,
    ROUND(AVG(CASE WHEN sh.ON_TIME_FLAG THEN 1 ELSE 0 END) * 100, 1) AS ON_TIME_PCT,
    ROUND(AVG(CASE WHEN sh.IN_FULL_FLAG THEN 1 ELSE 0 END) * 100, 1) AS IN_FULL_PCT,
    ROUND(AVG(CASE WHEN sh.ON_TIME_FLAG AND sh.IN_FULL_FLAG THEN 1 ELSE 0 END) * 100, 1) AS OTIF_PCT,
    ROUND(AVG(rcp.DAYS_LATE), 1) AS AVG_DAYS_LATE,
    SUM(CASE WHEN inv.MISMATCH_FLAG THEN 1 ELSE 0 END) AS INVOICE_MISMATCHES,
    ROUND(SUM(CASE WHEN inv.MISMATCH_FLAG THEN 1 ELSE 0 END)::FLOAT
          / NULLIF(COUNT(inv.INVOICE_ID), 0) * 100, 1) AS MISMATCH_RATE_PCT
FROM SPS_RETAIL_AI.SHARED.PURCHASE_ORDER po
JOIN SPS_RETAIL_AI.SHARED.RETAILER r ON po.RETAILER_ID = r.RETAILER_ID
LEFT JOIN SPS_RETAIL_AI.SHARED.SHIPMENT sh ON po.PO_ID = sh.PO_ID
LEFT JOIN SPS_RETAIL_AI.SHARED.INVOICE inv ON sh.SHIPMENT_ID = inv.SHIPMENT_ID
LEFT JOIN SPS_RETAIL_AI.SHARED.RECEIPT rcp ON sh.SHIPMENT_ID = rcp.SHIPMENT_ID
WHERE po.PO_VERSION = 1
GROUP BY 1, 2;

-- ── Foot Locker Views ───────────────────────────────────────
CREATE OR REPLACE VIEW FOOT_LOCKER.V_PURCHASE_ORDERS AS
SELECT po.*, l.BANNER, l.STORE_NAME, l.REGION, l.STATE
FROM SPS_RETAIL_AI.SHARED.PURCHASE_ORDER po
JOIN SPS_RETAIL_AI.SHARED.LOCATION l ON po.SHIP_TO_LOCATION_ID = l.LOCATION_ID
WHERE po.RETAILER_ID = 'FL';

CREATE OR REPLACE VIEW FOOT_LOCKER.V_WEEKLY_ACTIVITY AS
SELECT a.*, l.BANNER, l.STORE_NAME, l.REGION AS STORE_REGION, l.STATE AS STORE_STATE,
    i.STYLE_NUMBER, i.COLOR_NAME, i.SIZE_NAME, i.BRAND_NAME, i.MSRP AS ITEM_MSRP
FROM SPS_RETAIL_AI.SHARED.SPS_ACTIVITY a
JOIN SPS_RETAIL_AI.SHARED.LOCATION l ON a.LOCATION_ID = l.LOCATION_ID
JOIN SPS_RETAIL_AI.SHARED.ITEM i ON a.ITEM_ID = i.ITEM_ID
WHERE a.RETAILER_ID = 'FL';

-- ── Bass Pro Views ──────────────────────────────────────────
CREATE OR REPLACE VIEW BASS_PRO.V_PURCHASE_ORDERS AS
SELECT po.*, l.BANNER, l.STORE_NAME, l.REGION, l.STATE, l.CLIMATE
FROM SPS_RETAIL_AI.SHARED.PURCHASE_ORDER po
JOIN SPS_RETAIL_AI.SHARED.LOCATION l ON po.SHIP_TO_LOCATION_ID = l.LOCATION_ID
WHERE po.RETAILER_ID = 'BP';

CREATE OR REPLACE VIEW BASS_PRO.V_WEEKLY_ACTIVITY AS
SELECT a.*, l.BANNER, l.STORE_NAME, l.REGION AS STORE_REGION, l.STATE AS STORE_STATE, l.CLIMATE,
    i.STYLE_NUMBER, i.COLOR_NAME, i.SIZE_NAME, i.BRAND_NAME, i.MSRP AS ITEM_MSRP
FROM SPS_RETAIL_AI.SHARED.SPS_ACTIVITY a
JOIN SPS_RETAIL_AI.SHARED.LOCATION l ON a.LOCATION_ID = l.LOCATION_ID
JOIN SPS_RETAIL_AI.SHARED.ITEM i ON a.ITEM_ID = i.ITEM_ID
WHERE a.RETAILER_ID = 'BP';

-- ── Urban Outfitters Views ──────────────────────────────────
CREATE OR REPLACE VIEW URBAN_OUTFITTERS.V_PURCHASE_ORDERS AS
SELECT po.*, l.STORE_NAME, l.REGION, l.STATE,
    CASE WHEN po.IS_REPLACEMENT_850 THEN 'Replacement 850 (no 860s per URBN policy)' ELSE 'Original 850' END AS PO_TYPE_LABEL
FROM SPS_RETAIL_AI.SHARED.PURCHASE_ORDER po
JOIN SPS_RETAIL_AI.SHARED.LOCATION l ON po.SHIP_TO_LOCATION_ID = l.LOCATION_ID
WHERE po.RETAILER_ID = 'UO';

CREATE OR REPLACE VIEW URBAN_OUTFITTERS.V_WEEKLY_ACTIVITY AS
SELECT a.*, l.STORE_NAME, l.REGION AS STORE_REGION, l.STATE AS STORE_STATE,
    i.STYLE_NUMBER, i.COLOR_NAME, i.SIZE_NAME, i.BRAND_NAME, i.MSRP AS ITEM_MSRP,
    i.URBN_SHORT_SKU,
    xref.MAPPING_STATUS AS SKU_MAPPING_STATUS
FROM SPS_RETAIL_AI.SHARED.SPS_ACTIVITY a
JOIN SPS_RETAIL_AI.SHARED.LOCATION l ON a.LOCATION_ID = l.LOCATION_ID
JOIN SPS_RETAIL_AI.SHARED.ITEM i ON a.ITEM_ID = i.ITEM_ID
LEFT JOIN SPS_RETAIL_AI.URBAN_OUTFITTERS.SKU_CROSSWALK xref ON a.ITEM_ID = xref.ITEM_ID
WHERE a.RETAILER_ID = 'UO';
